language: cpp

dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q
  - sudo apt-get install flex
  - sudo apt-get install bison
  - sudo apt-get install libfl-dev
  - sudo apt-get install gcc-9 -qy
  - sudo apt-get install g++-9 -qy
  - sudo apt-get install clang-8 -qy
  - sudo apt-get install clang-tidy-8 -qy
  - sudo apt-get install clang-format-8 -qy
  - wget https://github.com/danmar/cppcheck/archive/1.86.tar.gz -P /tmp/
  - tar -xvf /tmp/1.86.tar.gz -C /tmp/
  - sudo make --directory=/tmp/cppcheck-1.86 install SRCDIR=build CFGDIR=/usr/share/cppcheck HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-sign-compare -Wno-unused-function" || true
  - wget http://ftp.gnu.org/gnu/bison/bison-3.5.3.tar.gz -P /tmp/
  - tar -xvf /tmp/bison-3.5.3.tar.gz -C /tmp/
  - pushd /tmp/bison-3.5.3 && ./configure && sudo make install && popd
  - sudo apt-get install python-pip
  - sudo pip install scan-build

env:
  - CLANG_TIDY=clang-tidy-8 CPPCHECK=cppcheck CC=clang-8 CXX=clang++-8
  - CLANG_TIDY=clang-tidy-8 CPPCHECK=cppcheck CC=gcc-9 CXX=g++-9

script:
  - make test -j
